version: "3.9"

services:

  # Mongo DB
  database_mongo:
    container_name: mongo_container
    image: "mongo:4.4.7"
    hostname: portfolio_mongo_host
    environment:
      MONGO_INITDB_ROOT_DATABASE: portfolio_mongo_db
    volumes:
      - mongodb_data:/data/db
    # neans you want to set data on container persist on your local folder named mongo-volume ./data/db is a folder that already created inside the mongo container.
    ports:
      - 27017:27017
    networks:
      - backend

  # Backend
  backend_spring:
    container_name: backend_container
    build:
      context: ./webflux-admin-app
      dockerfile: Dockerfile
    environment:
      # HOST_URL: portfolio-dev.club
      # HOST_PORT: 4200
      MONGO_URI: database_mongo
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@mail.me
    ports:
      - 8888:8080
    depends_on:
      - database_mongo
    networks:
      - backend

  # Frontend
  frontend_angular:
    container_name: frontend_container
    build:
      context: ./angular-admin-dashboard
      dockerfile: Dockerfile
    # environment:
      # HOST_URL: http://portfolio-dev.club
      # HOST_PORT: 4200
    ports:
      - 4200:80
    depends_on:
      - backend_spring
    networks:
      - frontend
      - backend

networks:
  backend:
    external: false
    name: backend
  frontend:
    external: false
    name: frontend

volumes:
  mongodb_data:
