version: "3.9"

services:
  # Mongo DB
  database_mongo:
    container_name: mongo_container
    image: mongo:latest
    hostname: portfolio_mongo_host
    environment:
      - MONGO_INITDB_ROOT_DATABASE=portfolio_mongo_db
    volumes:
      - mongodb_data:/data/db
    # neans you want to set data on container persist on your local folder named mongo-volume ./data/db is a folder that already created inside the mongo container.
    ports:
      - 27017:27017
    networks:
      - portfolio_net
  # Backend
  backend_spring:
    container_name: backend_container
    build:
      context: ./webflux-admin-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database_mongo
    networks:
      - portfolio_net
  # Frontend
  frontend_angular:
    container_name: frontend_container
    build:
      context: ./angular-admin-dashboard
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - portfolio_net

networks:
  portfolio_net:

volumes:
  mongodb_data:
